version: '3'

services:
###> doctrine/doctrine-bundle ###
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - symfony
  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - symfony
  db:
    image: postgres:latest
    container_name: symfony_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony

###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
  symfony:
    driver: bridge